version: "3"

services:
  server:
    image: judge0/judge0:1.13.0
    environment:
      - VIRTUAL_HOST=api.judge0.local
      - VIRTUAL_PORT=2358
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    depends_on:
      - db
      - redis

  worker:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    environment:
      - VIRTUAL_HOST=api.judge0.local
      - VIRTUAL_PORT=2358
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0
    environment:
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - POSTGRES_DB=judge0
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "judge0pass"'
    ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
